#!/bin/bash

# chk_2mv - eval positions in 2moves_v1.pgn.
#
#           To run:  ./chk_2mv >chk_2mv.out


# uci
# setoption name hash value 128
# setoption name threads value 4


export BOOK=2mv_v1.pgn
export ENGINE=./stockfish_sf9_2mv


\rm -f chk_2mv.posns

date
(  
  echo "uci"
  echo "setoption name hash value 128"
  echo "setoption name threads value 3"

  # for testing use:
  # grep FEN "$BOOK" | head -1000 |
  grep FEN "$BOOK" |
  while read line
  do
    #echo "$line" >>chk_2mv.posns
    echo "$line" | sed 's/.* "\([^"]*\)".*/position fen \1 0 3/'
    echo "go depth 18"
    sleep 0.9
  done
) | $ENGINE
date


# Then run this:
#     ./chk_2mv_2
# and this:
#     ./chk_2mv_3


